### ISSUE TITLE
Different video from url won't play in the demo

### ISSUE THREAD

**Issue by annagnavarro** [nfynt/com.nfynt.wvp#1]
I tried the demo here - https://nfynt.github.io/com.nfynt.wvp/ 
and input another url in the box - https://drive.google.com/uc?export=download&id=1P8umIJeo0Ohpkd8ot5VkhZ9HLOyQAFxG
and the video won't play. I tried playing it in the Unity Editor and the url works fine but the build won't play from another url.

**Comment by nfynt** [comment]
Hi @annagnavarro, 
AFAIK there's no easy or direct way of including video sources from google drive into a HTML5 video element, particularly due to CORS or permission restrictions. The URL you provided above is for downloading video and not the **video source URL**. Some browsers or media player (i.e. VLC, etc.) may attempt to download the video and try playing it locally if it's small enough (less than 100MB), but nothing that's a standard practice. Usually requires extra hackery either on client or server side.
With this plugin I only aim to support video sources supported from [HTML5 video](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video) element.
